name: Build
on: [push]
jobs:
  auto-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install black
        run: pip install black
      - name: Run black
        run: black api/app.py
  python-formatting-check:
    needs: auto-formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 --ignore=E501 api/app.py
  build-step:
    needs: python-formatting-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flask
        run: pip install flask
      - name: Install pytest
        run: pip install pytest
      - name: Install bs4
        run: pip install bs4
      - name: Install requests
        run: pip install requests
      - name: Run unit tests
        run: pytest api/app.py
  browser-tests:
    needs: build-step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pytest
        run: pip install pytest
      - name: Install bs4
        run: pip install bs4
      - name: Install requests
        run: pip install requests
      - name: Run browser tests
        run: pytest api/browser_test.py
  deploy-to-vercel:
    needs: browser-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'